### ISSUE TITLE
Loss did not decrease

### ISSUE THREAD

**Issue by shizhuoyang** [RiskySignal/Devil-Whisper-Attack#3]
Hello, I reproduced your work in docker, I used Microsoft's Azure API, set the target to “Hey Cortana send a text”, the initial audio is music/originalmusic1.wav, and I modified the pdf_path of mini and aspire to the corresponding CSV. However, it seems that the loss has not decreased during the training process, and the recognition results have not changed. Is it a problem with my step? Looking forward to your reply.

**Comment by RiskySignal** [comment]
I am not sure which part was wrong, would you give me more details？

**Comment by RiskySignal** [comment]
Thans for your feedback！ @shizhuoyang 

After a period of tests, we found that **the gradients can not converage on NVIDA GTX-30 and A100 gpus** when using our provided docker container. It is related to the fact that these gpus no longer support TF1. So **we suggest that it's better to reproduce our work on NVIDIA GTX-20/ TITAN-V gpus which is widely verifed on our server**.
